Repository soowan95/prj2-be, pull requests merged in 2023-12, with the labels that each got.

#33 Feat/soowan/insert song
  src/main/java/com/example/prj2be/controller/KakaoContoroller.java
  src/main/java/com/example/prj2be/controller/SongController.java
  src/main/java/com/example/prj2be/mapper/MemberMapper.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/service/KakaoService.java
  src/main/java/com/example/prj2be/service/MemberService.java
  src/main/java/com/example/prj2be/service/SongService.java
  src/main/java/com/example/prj2be/util/Parse.java
Labels: feat

#35 suggestion에서 playlist제목을 누르면 개인 차트가 나오는것
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/controller/SongController.java
  src/main/java/com/example/prj2be/controller/likeController.java
  src/main/java/com/example/prj2be/domain/Like.java
  src/main/java/com/example/prj2be/domain/MyPlaylist.java
  src/main/java/com/example/prj2be/mapper/LikeMapper.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
  src/main/java/com/example/prj2be/service/LikeService.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
  src/main/java/com/example/prj2be/service/SongService.java
Labels: feat

#38 1204back
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/controller/SongController.java
  src/main/java/com/example/prj2be/service/KakaoService.java
  src/main/java/com/example/prj2be/service/MemberService.java
Labels: fix

#45 Feet/jeongwon/comment
  src/main/java/com/example/prj2be/controller/CommentController.java
  src/main/java/com/example/prj2be/domain/Comment.java
  src/main/java/com/example/prj2be/mapper/CommentMapper.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/service/CommentService.java
  src/main/java/com/example/prj2be/service/SongService.java
Labels: feat

#46 Feat/mj/songlist
  src/main/java/com/example/prj2be/controller/SongController.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/service/SongService.java
Labels: feat

#49 Feat/euihyuk/playlist
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/controller/likeController.java
  src/main/java/com/example/prj2be/domain/Like.java
  src/main/java/com/example/prj2be/domain/MemberPlayList.java
  src/main/java/com/example/prj2be/domain/MyPlaylist.java
  src/main/java/com/example/prj2be/mapper/LikeMapper.java
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
  src/main/java/com/example/prj2be/service/LikeService.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
Labels: fix

#62 Test/soowan/live chat
  build.gradle
  src/main/java/com/example/prj2be/config/ChatConfig.java
  src/main/java/com/example/prj2be/controller/MemberController.java
  src/main/java/com/example/prj2be/controller/MessageController.java
  src/main/java/com/example/prj2be/domain/ChatMessage.java
  src/main/java/com/example/prj2be/domain/Member.java
  src/main/java/com/example/prj2be/mapper/ArtistMapper.java
  src/main/java/com/example/prj2be/mapper/MemberMapper.java
  src/main/java/com/example/prj2be/mapper/MessageMapper.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/service/MemberService.java
  src/main/java/com/example/prj2be/service/MessageService.java
  src/main/java/com/example/prj2be/service/SongService.java
Labels: test

#63 훈일 back
  src/main/java/com/example/prj2be/controller/MemberController.java
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/controller/likeController.java
  src/main/java/com/example/prj2be/domain/PlaylistLike.java
  src/main/java/com/example/prj2be/domain/SongLike.java
  src/main/java/com/example/prj2be/mapper/LikeMapper.java
  src/main/java/com/example/prj2be/mapper/MemberMapper.java
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
  src/main/java/com/example/prj2be/service/LikeService.java
  src/main/java/com/example/prj2be/service/MemberService.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
Labels: feat

#64 Feat/mj/picture1206
  build.gradle
  src/main/java/com/example/prj2be/config/AppConfig.java
  src/main/java/com/example/prj2be/controller/SongController.java
  src/main/java/com/example/prj2be/domain/Song.java
  src/main/java/com/example/prj2be/mapper/ArtistMapper.java
  src/main/java/com/example/prj2be/mapper/FileMapper.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/service/SongService.java
  src/main/resources/application.properties
Labels: feat

#65 Feat/euihyuk/1206
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/controller/SongController.java
  src/main/java/com/example/prj2be/controller/likeController.java
  src/main/java/com/example/prj2be/domain/MyPlaylist.java
  src/main/java/com/example/prj2be/mapper/LikeMapper.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
  src/main/java/com/example/prj2be/service/LikeService.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
  src/main/java/com/example/prj2be/service/SongService.java
Labels: feat

#66 Feet/jeongwon/password find
  src/main/java/com/example/prj2be/controller/MemberController.java
  src/main/java/com/example/prj2be/mapper/ArtistMapper.java
  src/main/java/com/example/prj2be/mapper/MemberMapper.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/service/MemberService.java
  src/main/java/com/example/prj2be/service/SongService.java
Labels: feat

#71 요청 확인 경로 변경
  src/main/java/com/example/prj2be/controller/SongController.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/service/SongService.java
Labels: feat

#69 Feat/hoonil/back 추천 플레이리스트
  src/main/java/com/example/prj2be/controller/MemberController.java
  src/main/java/com/example/prj2be/controller/MessageController.java
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/domain/Member.java
  src/main/java/com/example/prj2be/domain/MemberPlayList.java
  src/main/java/com/example/prj2be/mapper/LikeMapper.java
  src/main/java/com/example/prj2be/mapper/MemberMapper.java
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
  src/main/java/com/example/prj2be/service/KakaoService.java
  src/main/java/com/example/prj2be/service/MemberService.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
Labels: feat

#70 Feat/soowan/live chat
  src/main/java/com/example/prj2be/controller/MemberController.java
  src/main/java/com/example/prj2be/controller/MessageController.java
  src/main/java/com/example/prj2be/service/KakaoService.java
  src/main/java/com/example/prj2be/service/MemberService.java
  src/main/java/com/example/prj2be/service/SongService.java
  src/main/java/com/example/prj2be/util/Parse.java
Labels: feat

#80 Feat/hoonil/playlist backend
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/domain/MyPlaylist.java
  src/main/java/com/example/prj2be/domain/Song.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
  src/main/java/com/example/prj2be/service/MemberService.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
  src/main/java/com/example/prj2be/service/SongService.java
Labels: feat

#81 Feat/euihyuk/playlist view song
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/controller/SongController.java
  src/main/java/com/example/prj2be/domain/Member.java
  src/main/java/com/example/prj2be/domain/MyPlaylist.java
  src/main/java/com/example/prj2be/mapper/ArtistMapper.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
  src/main/java/com/example/prj2be/service/SongService.java
Labels: feat

#82 Modify/mj/song edit
  src/main/java/com/example/prj2be/controller/SongController.java
  src/main/java/com/example/prj2be/mapper/ArtistMapper.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/service/SongService.java
Labels: modify

#79 Modify/soowan/kako login
  src/main/java/com/example/prj2be/controller/KakaoContoroller.java
  src/main/java/com/example/prj2be/controller/MessageController.java
  src/main/java/com/example/prj2be/domain/ChatMessage.java
  src/main/java/com/example/prj2be/mapper/MemberMapper.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/service/KakaoService.java
  src/main/java/com/example/prj2be/service/MemberService.java
  src/main/java/com/example/prj2be/service/SongService.java
Labels: modify

#85 Feat/hoonil/create playlist back
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/domain/MemberPlayList.java
  src/main/java/com/example/prj2be/domain/MyPlaylist.java
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
Labels: feat

#86 /feat/euthyuk/삭제 기능 추가
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
Labels: feat

#83 Fix/soowan/update
  src/main/java/com/example/prj2be/controller/MemberController.java
  src/main/java/com/example/prj2be/controller/SongController.java
  src/main/java/com/example/prj2be/mapper/MemberMapper.java
  src/main/java/com/example/prj2be/mapper/MessageMapper.java
  src/main/java/com/example/prj2be/service/KakaoService.java
  src/main/java/com/example/prj2be/service/MemberService.java
  src/main/java/com/example/prj2be/service/SongService.java
Labels: fix

#88 Feat/soowan/delete member
  src/main/java/com/example/prj2be/controller/CommentController.java
  src/main/java/com/example/prj2be/controller/MemberController.java
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/domain/MyPlaylist.java
  src/main/java/com/example/prj2be/mapper/CommentMapper.java
  src/main/java/com/example/prj2be/mapper/LikeMapper.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
  src/main/java/com/example/prj2be/service/CommentService.java
  src/main/java/com/example/prj2be/service/MemberService.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
Labels: feat

#89 fix/플레이리스트 사진 안나오는 오류 수정
  src/main/java/com/example/prj2be/controller/MemberController.java
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/domain/MyPlaylist.java
  src/main/java/com/example/prj2be/mapper/MessageMapper.java
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
  src/main/java/com/example/prj2be/service/MemberService.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
Labels: fix

#90 playlist backend hoonil
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
Labels: fix

#92 fix/추천플레이리스트 사진 오류 수정
  src/main/java/com/example/prj2be/controller/SongController.java
  src/main/java/com/example/prj2be/domain/Song.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
  src/main/java/com/example/prj2be/service/SongService.java
Labels: fix

#91 1218 back
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/domain/MemberPlayList.java
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
Labels: feat

#93 modify/플레이리스트 view 수정
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
Labels: modify

#94 1219 back finish
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
Labels: fix

#95 Dev
  build.gradle
  src/main/java/com/example/prj2be/config/AppConfig.java
  src/main/java/com/example/prj2be/config/ChatConfig.java
  src/main/java/com/example/prj2be/controller/CommentController.java
  src/main/java/com/example/prj2be/controller/ControllerSuggestion.java
  src/main/java/com/example/prj2be/controller/KakaoContoroller.java
  src/main/java/com/example/prj2be/controller/MemberController.java
  src/main/java/com/example/prj2be/controller/MessageController.java
  src/main/java/com/example/prj2be/controller/PlaylistController.java
  src/main/java/com/example/prj2be/controller/SongController.java
  src/main/java/com/example/prj2be/controller/likeController.java
  src/main/java/com/example/prj2be/domain/ChatMessage.java
  src/main/java/com/example/prj2be/domain/Comment.java
  src/main/java/com/example/prj2be/domain/Member.java
  src/main/java/com/example/prj2be/domain/MemberPlayList.java
  src/main/java/com/example/prj2be/domain/MyPlaylist.java
  src/main/java/com/example/prj2be/domain/PlaylistLike.java
  src/main/java/com/example/prj2be/domain/Song.java
  src/main/java/com/example/prj2be/domain/SongLike.java
  src/main/java/com/example/prj2be/mapper/ArtistMapper.java
  src/main/java/com/example/prj2be/mapper/CommentMapper.java
  src/main/java/com/example/prj2be/mapper/FileMapper.java
  src/main/java/com/example/prj2be/mapper/LikeMapper.java
  src/main/java/com/example/prj2be/mapper/MemberMapper.java
  src/main/java/com/example/prj2be/mapper/MessageMapper.java
  src/main/java/com/example/prj2be/mapper/SongMapper.java
  src/main/java/com/example/prj2be/mapper/myPlaylistMapper.java
  src/main/java/com/example/prj2be/service/CommentService.java
  src/main/java/com/example/prj2be/service/KakaoService.java
  src/main/java/com/example/prj2be/service/LikeService.java
  src/main/java/com/example/prj2be/service/MemberService.java
  src/main/java/com/example/prj2be/service/MessageService.java
  src/main/java/com/example/prj2be/service/PlaylistService.java
  src/main/java/com/example/prj2be/service/SongService.java
  src/main/java/com/example/prj2be/util/Parse.java
  src/main/resources/application.properties
Labels: feat
